### ISSUE TITLE
The ImagePullSecret is not being taken into consideration

### ISSUE THREAD

**Issue by Taha1012** [kubeshark/kubeshark#1702]
**Describe the bug**
We have a configuration in place that requires us to retrieve Kubeshark images from a private registry using an ImagePullSecret. We have configured the ImagePullSecret in` .Values.tap.docker.imagePullSecrets`, but it seems that the configuration is not being acknowledged. We consistently encounter an ImagePullBackOff error. The same ImagePullSecret works as intended for other Pods within the cluster. Upon inspecting the deployment files, we discovered that the configuration for ImagePullSecret whis is done with this[ PR](https://github.com/kubeshark/kubeshark/pull/1602) is incorrectly positioned at the container level rather than at the spec level. 

**Provide more information**
Running on AKS

**To Reproduce**
1. Pull the helm chart
2. change the value file to change the registry to private registry
3. deploy the helm chart
4. See error "Error: ImagePullBackOff"

**Expected behavior**
the images from private registry will be pulled and used

**Comment by alongir** [comment]
Thanks for reporting this!

**Comment by corest** [comment]
Done

**Comment by Taha1012** [comment]
Hi @corest, thanks for your support. Unfortunately, still doesn't work

![Image](https://github.com/user-attachments/assets/3e641417-1779-4367-980b-a6c2758ee88f)

 the reference from values.yaml ist created

```
tap:
  docker:
    registry: <private-registry>
    tag: ""
    tagLocked: true
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: tsac-pull-secret
```
The secret also exists within the cluster; however, regrettably, it is still not being acknowledged.


The alignment here is also still incorrect. --> https://github.com/kubeshark/kubeshark/blob/e9796bfb2465f197140fc67090ac7f06356ccdca/helm-chart/templates/09-worker-daemon-set.yaml#L103
